[package]
authors = ["Jingcheng Yang <yjcyxky@163.com>"]
edition = "2018"
name = "preqc-pack"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9"
digest = "0.9.0"
exitcode = "1.1.2"
flate2 = {version = "1.0.19", features = ["zlib-ng-compat"], default-features = false}
lazy_static = "1.4.0"
log = "0.4.11"
md-5 = "0.9.1"
rayon = "1.4.0"
regex = "1.3.9"
rust-htslib = "0.32.0"
seq_io = "0.3.1"
serde = {version = "1.0.59", features = ["derive"]}
serde_json = "1.0.59"
stderrlog = "0.4.3"
structopt = "0.3.17"

[profile.release]
debug = false
opt-level = 3