[package]
authors = ["Jingcheng Yang <yjcyxky@163.com>"]
edition = "2018"
name = "preqc-pack"
version = "0.1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.2"
blake2 = "0.9"
digest = "0.9.0"
exitcode = "1.1.2"
fastq = "0.6.0"
lazy_static = "1.4.0"
log = "0.4.11"
md-5 = "0.9.1"
rayon = "1.4.0"
regex = "1.3.9"
rust-s3 = {version = "0.27.0-rc4", default-features = false, features = ["tokio-rustls-tls"]}
serde = {version = "1.0.59", features = ["derive"]}
serde_json = "1.0.59"
stderrlog = "0.4.3"
structopt = "0.3.17"
tokio = {version = "1", features = ["full"]}
futures = "0.3.5"
jemallocator = "0.3.2"
jemalloc-ctl = "0.3.2"

[dependencies.jemalloc-sys]
version = "0.3.2"
features = ["stats", "profiling", "unprefixed_malloc_on_supported_platforms"]

[profile.release]
debug = false
opt-level = 3
